### ISSUE TITLE
Support for using Groq as an alternative to OpenAI

### ISSUE THREAD

**Issue by bkataru** [ra-jeev/write-assist-ai#20]
I was wondering if there were any plans to extend the extension to allow for options that make it possible to specify GroqCloud instead of OpenAI as the LLM backend?

Groq provides access to a larger family of models including but not limited to the LLaMas, the Geminis, and the Mixtrals.

I'd assume the quickest way to do this with the project's current setup would be to expose a config option that allows one to change the LLM backend by changing the base URL that the `openai` library uses to direct network requests to, as described in Groq's [OpenAI Compatibility](https://console.groq.com/docs/openai) section.

```
import OpenAI from "openai";

const client = new OpenAI({
  apiKey: process.env.GROQ_API_KEY,
  baseURL: "https://api.groq.com/openai/v1"
});
```

Alternatively, there is the official `groq-typescript` package dedicated for integrating Groq into JS/TS applications.

Maybe this already exists but I was unable to find anything in the README about changing the base URL.

I would be happy to submit a PR with a possible integration if this is indeed something that is on the roadmap.

**Comment by ra-jeev** [comment]
This is a valid point @bkataru. I have already added the baseURL config to the codebase, just need to release the latest version and update the docs. 

Rest assured this is coming in the next release. :-)

**Comment by bkataru** [comment]
That's great to hear, looking forward to it!

**Comment by ra-jeev** [comment]
Released v0.5.0. Please check if it works correctly with your settings.

If you face any issue, pelase do let me know.

**Comment by bkataru** [comment]
It works like a charm! I've got `llama-3.1-70b-versatile` helping me write blog posts now. Thank you so much :)

**Comment by ra-jeev** [comment]
I will be adding a way to put 2 API Keys (one for OpenAI and one for the Proxy), and a toggle for using the ProxyURL so that one need not make it empty for easy switch to using OpenAI.

These changes should make it a better experience.
